services:
  postgres:
    image: postgres:16-alpine
    container_name: messaging_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: