"""user_id type

Revision ID: 6cbb7d39c83f
Revises: a376210a96ad
Create Date: 2026-03-09 16:49:20.025271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbb7d39c83f'
down_revision: Union[str, Sequence[str], None] = 'a376210a96ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
